name=FansElectronics_DMD32
version=1.0.0
author=Fans Electronics, Irfan Indra Kurniawan, S.T
maintainer=Irfan Indra Kurniawan, S.T <info@fanselectronics.com>
sentence=DMD32 Library for ESP32 HUB12 & HUB08 Support P10, P4.25, & P7.62.
paragraph=DMD32 Library for ESP32 HUB12 & HUB08 Support P10, P4.25, & P7.62. This library is designed to control DMD (Dot Matrix Display) panels using ESP32 microcontrollers. It provides functions to initialize the display, set pixel colors, and update the display with new data.
category=Display
url=https://github.com/Vean/FansElectronics_DMD32
architectures=esp32
license=MIT
includes=FansElectronics_DMD32.h
